_target_: mattstools.mattstools.transformers.FullTransformerEncoder
_partial_: True
node_embd_config: &densenet
    num_blocks: 1
    hddn_dim: 512
    nrm: layer
    act_h: lrlu
edge_embd_config: *densenet
te_config:
  model_dim: &dim 1024
  num_layers: &n_layers 8
  mha_config: &mha
    num_heads: 8
    drp: 0.1
    init_zeros: True
    do_layer_norm: True
  dense_config: &zeronet
    <<: *densenet
    output_init_zeros: True
outp_embd_config: *densenet